// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8oaAG5p0qvddbrRuSI7nF7isJ5ZxCsg',
    appId: '1:1003013199064:web:02a1d837a63abebebcb3ad',
    messagingSenderId: '1003013199064',
    projectId: 'notes-1b245',
    authDomain: 'notes-1b245.firebaseapp.com',
    storageBucket: 'notes-1b245.firebasestorage.app',
    measurementId: 'G-P8571Y48H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqurup4wrK6ejIdnDQ7jlnLDRQR81T86g',
    appId: '1:1003013199064:android:9719d514591e500bbcb3ad',
    messagingSenderId: '1003013199064',
    projectId: 'notes-1b245',
    storageBucket: 'notes-1b245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzp1bUGSjgNaL9I7H8f1LrMFvfL-aqS6w',
    appId: '1:1003013199064:ios:bfa36d7cb2b96dd7bcb3ad',
    messagingSenderId: '1003013199064',
    projectId: 'notes-1b245',
    storageBucket: 'notes-1b245.firebasestorage.app',
    iosBundleId: 'com.talimkar.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzp1bUGSjgNaL9I7H8f1LrMFvfL-aqS6w',
    appId: '1:1003013199064:ios:bfa36d7cb2b96dd7bcb3ad',
    messagingSenderId: '1003013199064',
    projectId: 'notes-1b245',
    storageBucket: 'notes-1b245.firebasestorage.app',
    iosBundleId: 'com.talimkar.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8oaAG5p0qvddbrRuSI7nF7isJ5ZxCsg',
    appId: '1:1003013199064:web:05b456a2b857ef76bcb3ad',
    messagingSenderId: '1003013199064',
    projectId: 'notes-1b245',
    authDomain: 'notes-1b245.firebaseapp.com',
    storageBucket: 'notes-1b245.firebasestorage.app',
    measurementId: 'G-50MJDWWP78',
  );
}
